# Generated by Django 5.2.11 on 2026-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST')], max_length=100),
        ),
    ]
