# Generated by Django 5.2.11 on 2026-03-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_remove_student_id_alter_student_osis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('current_condition', models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST')], max_length=7)),
                ('owner', models.ForeignKey(default='000000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='student.student')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
            ],
        ),
    ]
