# Generated by Django 5.2.11 on 2026-02-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_remove_student_id_alter_student_osis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('BAG', 'CAMERA BAG'), ('NXBAT', 'CAMERA BATTERY'), ('BOOM', 'BOOM POLE'), ('PHBKT', 'PHONE BRACKET'), ('TBBKT', 'TABLET BRACKET'), ('BCHG', 'CAM BATTERY CHARGER'), ('NX100', 'CAMERA'), ('HND', 'HANDHELD MIC'), ('HDPH', 'HEADPHONES'), ('IPAD', 'IPAD'), ('LAPCHRG', 'LAPTOP CHARGER'), ('LAV', 'LAV MIC'), ('LED', 'LED LIGHT'), ('TSC-SD', 'TASCAM SD CARD'), ('SD', 'SD CARD'), ('SHGN', 'SHOTGUN MIC'), ('TSCM', 'TASCAM'), ('TPD', 'TRIPOD INTRO'), ('MANF', 'TRIPOD ADV'), ('MONPD', 'MONOPOD'), ('XLR', 'XLR CABLE')], max_length=7)),
                ('owner', models.ForeignKey(default='000000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='student.student')),
            ],
        ),
    ]
