# Generated by Django 5.2.11 on 2026-03-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_current_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='current_condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST')], max_length=7),
        ),
    ]
