# Generated by Django 5.2.11 on 2026-02-04 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='osis',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
